version: '3.8'

services:
  service-c:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-c
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ORDER_SERVICE_URL=http://service-b:8081
    networks:
      - geosapiens
    restart: unless-stopped

networks:
  geosapiens:
    external: true

