version: '3.8'

services:
  service-c:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: service-c
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - ORDER_SERVICE_URL=http://host.docker.internal:8081
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped

